-- MySQL Script generated by MySQL Workbench
-- Wed Jul 26 15:02:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema u206369201_mig_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema u206369201_mig_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u206369201_mig_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `u206369201_mig_db` ;

-- -----------------------------------------------------
-- Table `u206369201_mig_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_mig_db`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(155) NOT NULL,
  `color` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u206369201_mig_db`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_mig_db`.`status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NOT NULL,
  `delay` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u206369201_mig_db`.`ideas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_mig_db`.`ideas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `id_status` INT(11) NOT NULL,
  `deadline` DATE NOT NULL,
  `detail` MEDIUMTEXT NOT NULL,
  `risk` MEDIUMTEXT NOT NULL,
  `benefit` MEDIUMTEXT NOT NULL,
  `impact` MEDIUMTEXT NOT NULL,
  `is_closed` TINYINT(4) NOT NULL,
  `delay_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_idea_status` (`id_status` ASC) VISIBLE,
  CONSTRAINT `fk_idea_status`
    FOREIGN KEY (`id_status`)
    REFERENCES `u206369201_mig_db`.`status` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 79
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u206369201_mig_db`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_mig_db`.`locations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(155) NOT NULL,
  `region` VARCHAR(155) NOT NULL,
  `country` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u206369201_mig_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_mig_db`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u206369201_mig_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_mig_db`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(150) NOT NULL,
  `lastname` VARCHAR(150) NOT NULL,
  `occupation` VARCHAR(150) NOT NULL DEFAULT '',
  `service` VARCHAR(150) NOT NULL DEFAULT '',
  `picture` VARCHAR(150) NOT NULL DEFAULT '',
  `phone` VARCHAR(40) NULL DEFAULT '',
  `email` VARCHAR(250) NOT NULL,
  `hashed_password` VARCHAR(255) NOT NULL,
  `id_role` INT(11) NOT NULL DEFAULT 1,
  `id_location` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_location` (`id_location` ASC) VISIBLE,
  INDEX `fk_user_role` (`id_role` ASC) VISIBLE,
  CONSTRAINT `fk_user_location`
    FOREIGN KEY (`id_location`)
    REFERENCES `u206369201_mig_db`.`locations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`id_role`)
    REFERENCES `u206369201_mig_db`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 77
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u206369201_mig_db`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_mig_db`.`comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NULL DEFAULT NULL,
  `id_comment` INT(11) NULL DEFAULT NULL,
  `id_user` INT(11) NOT NULL,
  `id_idea` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_idea` (`id_idea` ASC) VISIBLE,
  INDEX `fk_comment_response` (`id_comment` ASC) VISIBLE,
  INDEX `fk_comment_user` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_comment_idea`
    FOREIGN KEY (`id_idea`)
    REFERENCES `u206369201_mig_db`.`ideas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment_response`
    FOREIGN KEY (`id_comment`)
    REFERENCES `u206369201_mig_db`.`comments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `u206369201_mig_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 126
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u206369201_mig_db`.`ideas_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_mig_db`.`ideas_has_categories` (
  `id_idea` INT(11) NOT NULL,
  `id_category` INT(11) NOT NULL,
  PRIMARY KEY (`id_idea`, `id_category`),
  INDEX `fk_ideas_has_category` (`id_category` ASC) VISIBLE,
  CONSTRAINT `fk_ideas_has_categories_idea`
    FOREIGN KEY (`id_idea`)
    REFERENCES `u206369201_mig_db`.`ideas` (`id`),
  CONSTRAINT `fk_ideas_has_category`
    FOREIGN KEY (`id_category`)
    REFERENCES `u206369201_mig_db`.`categories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u206369201_mig_db`.`ideas_has_locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_mig_db`.`ideas_has_locations` (
  `id_idea` INT(11) NOT NULL,
  `id_location` INT(11) NOT NULL,
  PRIMARY KEY (`id_idea`, `id_location`),
  INDEX `fk_ideas_has_locations_location` (`id_location` ASC) VISIBLE,
  CONSTRAINT `fk_ideas_has_locations_idea`
    FOREIGN KEY (`id_idea`)
    REFERENCES `u206369201_mig_db`.`ideas` (`id`),
  CONSTRAINT `fk_ideas_has_locations_location`
    FOREIGN KEY (`id_location`)
    REFERENCES `u206369201_mig_db`.`locations` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u206369201_mig_db`.`users_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_mig_db`.`users_has_categories` (
  `id_user` INT(11) NOT NULL,
  `id_category` INT(11) NOT NULL,
  PRIMARY KEY (`id_user`, `id_category`),
  INDEX `fk_users_has_categories_category` (`id_category` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_categories_category`
    FOREIGN KEY (`id_category`)
    REFERENCES `u206369201_mig_db`.`categories` (`id`),
  CONSTRAINT `fk_users_has_categories_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `u206369201_mig_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u206369201_mig_db`.`users_has_ideas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_mig_db`.`users_has_ideas` (
  `id_user` INT(11) NOT NULL,
  `id_idea` INT(11) NOT NULL,
  `is_owner` TINYINT(4) NOT NULL,
  `has_voted` TINYINT(4) NOT NULL,
  `vote_value` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`, `id_idea`),
  INDEX `fk_users_has_ideas_idea` (`id_idea` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_ideas_idea`
    FOREIGN KEY (`id_idea`)
    REFERENCES `u206369201_mig_db`.`ideas` (`id`),
  CONSTRAINT `fk_users_has_ideas_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `u206369201_mig_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;